homepage: https://github.com/nerdrew/dart-ctags
description: ctags compatible tag file generator for dart code
name: dart_ctags
version: 1.2.3-null-safety
environment:
    sdk: '>=2.12.0 <3.0.0'
executables:
    dart_ctags: tags
dependencies:
    analyzer: ^1.5.0 
    path: ^1.8.0 
    args: ^2.1.0 
dev_dependencies:
    pedantic: ^1.11.0 
